{
  "debianbug": 758772,
  "description": "PIL/IcnsImagePlugin.py in Python Imaging Library (PIL) and Pillow before 2.3.2 and 2.5.x before 2.5.2 allows remote attackers to cause a denial of service via a crafted block size.",
  "releases": {
    "bullseye": {
      "fixed_version": "2.5.3-1",
      "repositories": {
        "bullseye": "6.1.0-1"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "buster": {
      "fixed_version": "2.5.3-1",
      "repositories": {
        "buster": "5.4.1-2"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "jessie": {
      "fixed_version": "2.5.3-1",
      "repositories": {
        "jessie": "2.6.1-2+deb8u3",
        "jessie-security": "2.6.1-2+deb8u3"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "sid": {
      "fixed_version": "2.5.3-1",
      "repositories": {
        "sid": "6.1.0-1"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "stretch": {
      "fixed_version": "2.5.3-1",
      "repositories": {
        "stretch": "4.0.0-4"
      },
      "status": "resolved",
      "urgency": "medium**"
    }
  },
  "scope": "remote"
}