{
  "debianbug": 628453,
  "description": "The urllib and urllib2 modules in Python 2.x before 2.7.2 and 3.x before 3.2.1 process Location headers that specify redirection to file: URLs, which makes it easier for remote attackers to obtain sensitive information or cause a denial of service (resource consumption) via a crafted URL, as demonstrated by the file:///etc/passwd and file:///dev/zero URLs.",
  "releases": {
    "bullseye": {
      "fixed_version": "2.7.1-7",
      "repositories": {
        "bullseye": "2.7.16-3"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "buster": {
      "fixed_version": "2.7.1-7",
      "repositories": {
        "buster": "2.7.16-2"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "jessie": {
      "fixed_version": "2.7.1-7",
      "repositories": {
        "jessie": "2.7.9-2+deb8u1",
        "jessie-security": "2.7.9-2+deb8u4"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "sid": {
      "fixed_version": "2.7.1-7",
      "repositories": {
        "sid": "2.7.16-3"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "stretch": {
      "fixed_version": "2.7.1-7",
      "repositories": {
        "stretch": "2.7.13-2+deb9u3",
        "stretch-security": "2.7.13-2+deb9u3"
      },
      "status": "resolved",
      "urgency": "medium**"
    }
  },
  "scope": "remote"
}