{
  "debianbug": 599739,
  "description": "Multiple integer overflows in audioop.c in the audioop module in Python 2.6, 2.7, 3.1, and 3.2 allow context-dependent attackers to cause a denial of service (application crash) via a large fragment, as demonstrated by a call to audioop.lin2lin with a long string in the first argument, leading to a buffer overflow.  NOTE: this vulnerability exists because of an incorrect fix for CVE-2008-3143.5.",
  "releases": {
    "bullseye": {
      "fixed_version": "2.7-1",
      "repositories": {
        "bullseye": "2.7.16-3"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "buster": {
      "fixed_version": "2.7-1",
      "repositories": {
        "buster": "2.7.16-2"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "jessie": {
      "fixed_version": "2.7-1",
      "repositories": {
        "jessie": "2.7.9-2+deb8u1",
        "jessie-security": "2.7.9-2+deb8u4"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "sid": {
      "fixed_version": "2.7-1",
      "repositories": {
        "sid": "2.7.16-3"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "stretch": {
      "fixed_version": "2.7-1",
      "repositories": {
        "stretch": "2.7.13-2+deb9u3",
        "stretch-security": "2.7.13-2+deb9u3"
      },
      "status": "resolved",
      "urgency": "low"
    }
  },
  "scope": "remote"
}