{
  "debianbug": 925285,
  "description": "ZNC before 1.7.3-rc1 allows an existing remote user to cause a Denial of Service (crash) via invalid encoding.",
  "releases": {
    "bullseye": {
      "fixed_version": "1.7.2-2",
      "repositories": {
        "bullseye": "1.7.4-7"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "buster": {
      "fixed_version": "1.7.2-2",
      "repositories": {
        "buster": "1.7.2-3"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "jessie": {
      "nodsa": "Minor issue, workaround is to disable modpython",
      "nodsa_reason": "ignored",
      "repositories": {
        "jessie": "1.4-2",
        "jessie-security": "1.4-2+deb8u2"
      },
      "status": "open",
      "urgency": "medium**"
    },
    "sid": {
      "fixed_version": "1.7.2-2",
      "repositories": {
        "sid": "1.7.4-7"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "stretch": {
      "fixed_version": "1.6.5-1+deb9u2",
      "repositories": {
        "stretch": "1.6.5-1+deb9u1",
        "stretch-security": "1.6.5-1+deb9u2"
      },
      "status": "resolved",
      "urgency": "medium**"
    }
  },
  "scope": "remote"
}