{
  "debianbug": 337334,
  "description": "OpenVPN 2.x before 2.0.4, when running in TCP mode, allows remote attackers to cause a denial of service (segmentation fault) by forcing the accept function call to return an error status, which leads to a null dereference in an exception handler.",
  "releases": {
    "bullseye": {
      "fixed_version": "2.0.5-1",
      "repositories": {
        "bullseye": "2.4.7-1"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "buster": {
      "fixed_version": "2.0.5-1",
      "repositories": {
        "buster": "2.4.7-1"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "jessie": {
      "fixed_version": "2.0.5-1",
      "repositories": {
        "jessie": "2.3.4-5+deb8u2",
        "jessie-security": "2.3.4-5+deb8u2"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "sid": {
      "fixed_version": "2.0.5-1",
      "repositories": {
        "sid": "2.4.7-1"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "stretch": {
      "fixed_version": "2.0.5-1",
      "repositories": {
        "stretch": "2.4.0-6+deb9u3",
        "stretch-security": "2.4.0-6+deb9u1"
      },
      "status": "resolved",
      "urgency": "low"
    }
  },
  "scope": "remote"
}