{
  "description": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause a use-after-free in ext4_xattr_set_entry function and a denial of service or unspecified other impact may occur by renaming a file in a crafted ext4 filesystem image.",
  "releases": {
    "bullseye": {
      "fixed_version": "4.17.3-1",
      "repositories": {
        "bullseye": "5.2.9-2"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "buster": {
      "fixed_version": "4.17.3-1",
      "repositories": {
        "buster": "4.19.37-5",
        "buster-security": "4.19.37-5+deb10u2"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "jessie": {
      "fixed_version": "3.16.59-1",
      "repositories": {
        "jessie": "3.16.56-1+deb8u1",
        "jessie-security": "3.16.72-1"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "sid": {
      "fixed_version": "4.17.3-1",
      "repositories": {
        "sid": "5.2.9-2"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "stretch": {
      "fixed_version": "4.9.110-1",
      "repositories": {
        "stretch": "4.9.168-1",
        "stretch-security": "4.9.168-1+deb9u5"
      },
      "status": "resolved",
      "urgency": "medium**"
    }
  },
  "scope": "local"
}