{
  "description": "An issue was discovered in fs/xfs/xfs_super.c in the Linux kernel before 4.18. A use after free exists, related to xfs_fs_fill_super failure.",
  "releases": {
    "bullseye": {
      "fixed_version": "4.18.6-1",
      "repositories": {
        "bullseye": "5.2.9-2"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "buster": {
      "fixed_version": "4.18.6-1",
      "repositories": {
        "buster": "4.19.37-5",
        "buster-security": "4.19.37-5+deb10u2"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "jessie": {
      "repositories": {
        "jessie": "3.16.56-1+deb8u1",
        "jessie-security": "3.16.72-1"
      },
      "status": "open",
      "urgency": "medium**"
    },
    "sid": {
      "fixed_version": "4.18.6-1",
      "repositories": {
        "sid": "5.2.9-2"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "stretch": {
      "repositories": {
        "stretch": "4.9.168-1",
        "stretch-security": "4.9.168-1+deb9u5"
      },
      "status": "open",
      "urgency": "medium**"
    }
  },
  "scope": "local"
}