{
  "affected_release": [
    {
      "advisory": "RHSA-2019:1467",
      "cpe": "cpe:/o:redhat:enterprise_linux:6",
      "package": "python-2.6.6-68.el6_10",
      "product_name": "Red Hat Enterprise Linux 6",
      "release_date": "2019-06-13T00:00:00"
    },
    {
      "advisory": "RHSA-2019:0710",
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "package": "python-2.7.5-77.el7_6",
      "product_name": "Red Hat Enterprise Linux 7",
      "release_date": "2019-04-08T00:00:00"
    },
    {
      "advisory": "RHBA-2019:0763",
      "cpe": "cpe:/o:redhat:enterprise_linux:7::hypervisor",
      "package": "redhat-virtualization-host-0:4.2-20190411.1.el7_6",
      "product_name": "Red Hat Virtualization 4 Management Agent for RHEL 7 Hosts",
      "release_date": "2019-04-16T00:00:00"
    },
    {
      "advisory": "RHBA-2019:0764",
      "cpe": "cpe:/o:redhat:enterprise_linux:7::hypervisor",
      "package": "rhvm-appliance-0:4.2-20190411.1.el7",
      "product_name": "Red Hat Virtualization 4 Management Agent for RHEL 7 Hosts",
      "release_date": "2019-04-16T00:00:00"
    },
    {
      "advisory": "RHSA-2019:0997",
      "cpe": "cpe:/o:redhat:enterprise_linux:8",
      "package": "python3-3.6.8-2.el8_0",
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2019-05-07T00:00:00"
    },
    {
      "advisory": "RHSA-2019:0981",
      "cpe": "cpe:/a:redhat:enterprise_linux:8",
      "package": "python27:2.7-8000020190410132513.c0efe978",
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2019-05-07T00:00:00"
    },
    {
      "advisory": "RHSA-2019:0765",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el6",
      "package": "rh-python36-python-3.6.3-4.el6",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 6",
      "release_date": "2019-04-16T00:00:00"
    },
    {
      "advisory": "RHSA-2019:0806",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el6",
      "package": "python27-python-2.7.13-4.el6",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 6",
      "release_date": "2019-04-23T00:00:00"
    },
    {
      "advisory": "RHSA-2019:0902",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el6",
      "package": "rh-python35-python-3.5.1-12.el6",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 6",
      "release_date": "2019-04-30T00:00:00"
    },
    {
      "advisory": "RHSA-2019:0765",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7",
      "package": "rh-python36-python-3.6.3-7.el7",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7",
      "release_date": "2019-04-16T00:00:00"
    },
    {
      "advisory": "RHSA-2019:0806",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7",
      "package": "python27-python-2.7.13-6.el7",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7",
      "release_date": "2019-04-23T00:00:00"
    },
    {
      "advisory": "RHSA-2019:0902",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7",
      "package": "rh-python35-python-3.5.1-12.el7",
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7",
      "release_date": "2019-04-30T00:00:00"
    }
  ],
  "bugzilla": {
    "description": "\nCVE-2019-9636 python: Information Disclosure due to urlsplit improper NFKC normalization\n    ",
    "id": "1688543",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1688543"
  },
  "cvss3": {
    "cvss3_base_score": "9.8",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "status": "verified"
  },
  "cwe": "CWE-172",
  "details": [
    "\nPython 2.7.x through 2.7.16 and 3.x through 3.7.2 is affected by: Improper Handling of Unicode Encoding (with an incorrect netloc) during NFKC normalization. The impact is: Information disclosure (credentials, cookies, etc. that are cached against a given hostname). The components are: urllib.parse.urlsplit, urllib.parse.urlparse. The attack vector is: A specially crafted URL could be incorrectly parsed to locate cookies or authentication data and send that information to a different host than when parsed correctly.\n    ",
    "\nIt was discovered that python's functions urllib.parse.urlsplit and urllib.parse.urlparse do not properly handle URLs encoded with Punycode/Internationalizing Domain Names in Applications (IDNA), which may result in a wrong domain name (specifically the netloc component of URL - user@domain:port) being returned by those functions. When an application parses user-supplied URLs to store cookies, authentication credentials, or other kind of information, it is possible for an attacker to provide specially crafted URLs to make the application locate host-related information (e.g. cookies, authentication data) and send them to a different host than where it should, unlike if the URLs had been correctly parsed. The result of an attack may vary based on the application.\n    "
  ],
  "name": "CVE-2019-9636",
  "package_state": [
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:5",
      "fix_state": "Out of support scope",
      "package_name": "python",
      "product_name": "Red Hat Enterprise Linux 5"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "fix_state": "Not affected",
      "package_name": "python3",
      "product_name": "Red Hat Enterprise Linux 7"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:8",
      "fix_state": "Not affected",
      "package_name": "python36:3.6/python36",
      "product_name": "Red Hat Enterprise Linux 8"
    }
  ],
  "public_date": "2019-03-06T00:00:00",
  "references": [
    "\nhttps://python-security.readthedocs.io/vuln/urlsplit-nfkc-normalization.html\n    "
  ],
  "threat_severity": "Important",
  "upstream_fix": "python 3.5.7, python 3.7.3"
}