{
  "bugzilla": {
    "description": "\nCVE-2019-12219 SDL: invalid free error in function SDL_SetError_REAL\n    ",
    "id": "1732258",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1732258"
  },
  "cvss3": {
    "cvss3_base_score": "3.3",
    "cvss3_scoring_vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
    "status": "draft"
  },
  "details": [
    "\nAn issue was discovered in libSDL2.a in Simple DirectMedia Layer (SDL) 2.0.9 when used in conjunction with libSDL2_image.a in SDL2_image 2.0.4. There is an invalid free error in the SDL function SDL_SetError_REAL at SDL_error.c.\n    "
  ],
  "name": "CVE-2019-12219",
  "package_state": [
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:5",
      "fix_state": "New",
      "package_name": "SDL",
      "product_name": "Red Hat Enterprise Linux 5"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:6",
      "fix_state": "New",
      "package_name": "SDL",
      "product_name": "Red Hat Enterprise Linux 6"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:7",
      "fix_state": "New",
      "package_name": "SDL",
      "product_name": "Red Hat Enterprise Linux 7"
    },
    {
      "cpe": "cpe:/o:redhat:enterprise_linux:8",
      "fix_state": "New",
      "package_name": "SDL",
      "product_name": "Red Hat Enterprise Linux 8"
    }
  ],
  "public_date": "2019-05-20T00:00:00",
  "threat_severity": "Low"
}