{
  "debianbug": 919249,
  "description": "murmur in Mumble through 1.2.19 before 2018-08-31 mishandles multiple concurrent requests that are persisted in the database, which allows remote attackers to cause a denial of service (daemon hang or crash) via a message flood.",
  "releases": {
    "bullseye": {
      "fixed_version": "1.3.0~git20190114.9fcc588+dfsg-1",
      "repositories": {
        "bullseye": "1.3.0~git20190125.440b173+dfsg-2"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "buster": {
      "fixed_version": "1.3.0~git20190114.9fcc588+dfsg-1",
      "repositories": {
        "buster": "1.3.0~git20190125.440b173+dfsg-2"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "jessie": {
      "fixed_version": "1.2.8-2+deb8u1",
      "repositories": {
        "jessie": "1.2.8-2",
        "jessie-security": "1.2.8-2+deb8u1"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "sid": {
      "fixed_version": "1.3.0~git20190114.9fcc588+dfsg-1",
      "repositories": {
        "sid": "1.3.0~git20190125.440b173+dfsg-2"
      },
      "status": "resolved",
      "urgency": "medium**"
    },
    "stretch": {
      "fixed_version": "1.2.18-1+deb9u1",
      "repositories": {
        "stretch": "1.2.18-1+deb9u1",
        "stretch-security": "1.2.18-1+deb9u1"
      },
      "status": "resolved",
      "urgency": "medium**"
    }
  },
  "scope": "remote"
}