{
  "description": "Ansible 2.5 prior to 2.5.5, and 2.4 prior to 2.4.5, do not honor the no_log task flag for failed tasks. When the no_log flag has been used to protect sensitive data passed to a task from being logged, and that task does not run successfully, Ansible will expose sensitive data in log files and on the terminal of the user running Ansible.",
  "releases": {
    "bullseye": {
      "fixed_version": "2.5.5+dfsg-1",
      "repositories": {
        "bullseye": "2.7.8+dfsg-1"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "buster": {
      "fixed_version": "2.5.5+dfsg-1",
      "repositories": {
        "buster": "2.7.7+dfsg-1"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "jessie": {
      "fixed_version": "0",
      "repositories": {
        "jessie": "1.7.2+dfsg-2",
        "jessie-security": "1.7.2+dfsg-2+deb8u1"
      },
      "status": "resolved",
      "urgency": "unimportant"
    },
    "sid": {
      "fixed_version": "2.5.5+dfsg-1",
      "repositories": {
        "sid": "2.8.3+dfsg-1"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "stretch": {
      "fixed_version": "2.2.1.0-2+deb9u1",
      "repositories": {
        "stretch": "2.2.1.0-2+deb9u1",
        "stretch-security": "2.2.1.0-2+deb9u1"
      },
      "status": "resolved",
      "urgency": "medium**"
    }
  },
  "scope": "remote"
}